### ISSUE TITLE
Home logo breaks when navigating through the project

### ISSUE THREAD

**Issue by oparoz** [phsteffen/kanboard-themeplus#1]
A relative URL cannot be used here:
https://github.com/phsteffen/kanboard-themeplus/blob/master/dist/Themeplus/Template/layout/header.php#L6

**Comment by oparoz** [comment]
Same problem when loading CSS stylesheets.

The solution is to use `$this->url->dir()` as a prefix.

**Comment by oparoz** [comment]
Same problem with login logo

**Comment by oparoz** [comment]
Ping @phsteffen

**Comment by phsteffen** [comment]
Hi Oparoz,

i add your solution with the prefix.
Thanx :)

Philip
