### ISSUE TITLE
Version 1.2.4 Compatibility - Logo 

### ISSUE THREAD

**Issue by tobycolledge** [phsteffen/kanboard-themeplus#13]
Hi,

The project board does not display when using a custom logo in the latest version 1.2.4, all other pages display correctly.

Error message:
( ! ) Fatal error: Call to undefined method Kanboard\Helper\TextHelper::markdownAttribute() in C:\wamp\www\kanboard\plugins\Themeplus\Template\layout\header\title.php on line 14 Call Stack #TimeMemoryFunctionLocation 10.0007132760{main}( )...\index.php:0 20.22055034504Kanboard\Core\Controller\Runner->execute( )...\index.php:9 30.26595846200Kanboard\Core\Controller\Runner->executeController( )...\Runner.php:31 40.26855917632Kanboard\Controller\BoardViewController->show( )...\Runner.php:77 50.31556621496Kanboard\Helper\LayoutHelper->app( )...\BoardViewController.php:71 60.31836622664Kanboard\Helper\LayoutHelper->pageLayout( )...\LayoutHelper.php:40 70.35626907368Kanboard\Core\Template->render( )...\LayoutHelper.php:187 80.35696967440include( 'C:\wamp\www\kanboard\app\Template\layout.php' )...\Template.php:83 90.36136978216Kanboard\Core\Template->render( )...\layout.php:65 100.36187002072include( 'C:\wamp\www\kanboard\app\Template\header.php' )...\Template.php:83 110.36187002504Kanboard\Core\Template->render( )...\header.php:6 120.36247027688include( 'C:\wamp\www\kanboard\plugins\Themeplus\Template\layout\header\title.php' )...\Template.php:8

**Comment by mauricio-sonegatti** [comment]
I'm having problems on the BoardViewController with 1.2.4, nothing is showing.

**Comment by Gaverek** [comment]
Same problem here, any updates on your cases?
