### ISSUE TITLE
Setting logo in Kanboard 1.2.4 causes PHP fatal error

### ISSUE THREAD

**Issue by funkypenguin** [phsteffen/kanboard-themeplus#14]
Hi,

Thank you for your plugin :)

I've noticed a fault with Kanboard 1.2.4 - When I set ```$themePlusConfig['logo'] = 'favicon-32x32.png';``` in config.php (and the image does exist), I get the following error when using Kanboard: 

```
kanboard_app.1.ytqjmb6h0p93@ds3    | 2018/06/07 11:02:40 [error] 14#14: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method Kanboard\Helper\TextHelper::markdownAttribute() in /var/www/app/plugins/Themeplus/Template/layout/header/title.php:14
kanboard_app.1.ytqjmb6h0p93@ds3    | Stack trace:
kanboard_app.1.ytqjmb6h0p93@ds3    | #0 /var/www/app/app/Core/Template.php(83): include()
kanboard_app.1.ytqjmb6h0p93@ds3    | #1 /var/www/app/app/Template/header.php(5): Kanboard\Core\Template->render('header/title', Array)
kanboard_app.1.ytqjmb6h0p93@ds3    | #2 /var/www/app/app/Core/Template.php(83): include('/var/www/app/ap...')
kanboard_app.1.ytqjmb6h0p93@ds3    | #3 /var/www/app/app/Template/layout.php(62): Kanboard\Core\Template->render('header', Array)
kanboard_app.1.ytqjmb6h0p93@ds3    | #4 /var/www/app/app/Core/Template.php(83): include('/var/www/app/ap...')
kanboard_app.1.ytqjmb6h0p93@ds3    | #5 /var/www/app/app/Helper/LayoutHelper.php(186): Kanboard\Core\Template->render('layout', Array)
kanboard_app.1.ytqjmb6h0p93@ds3    | #6 /var/www/app/app/Helper/LayoutHelper.php(40): Kanboard\Helper\LayoutHelper->pageLayout('board/view_priv...', Array)
kanboard_app.1.ytqjmb6h0p93@ds3    | #7 /var/www/app/app/Controller/BoardViewController.php(70): Kanboard\Helper\LayoutHelper->app('board/view_priv...', Array)
kanboard_app.1.ytqjmb6h0p93@ds3    | #8 /var/www/app/app/Core/Controller/Runner.php(77): Kanboard\Controller\BoardViewContro" while reading response header from upstream, client: 172.16.8.5, server: localhost, request: "GET /?controller=BoardViewController&action=show&project_id=3&search=status%3Aopen HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "kanboard.funkypenguin.co.nz"
```
Any advice would be appreciated ;)

D

**Comment by dahmen** [comment]
I have the same issue in Kanboard 1.2.4 - 

Line 14 in title.php:
`<small class="tooltip" title="<?= $this->text->markdownAttribute($description) ?>">`

In KanBoard there is not existing the "markdownAttribute" Method anymore.

My "fast repair" is to make the following change to title.php [use on own risk!]
old code:
`    <?php if (! empty($description)): ?>
        <small class="tooltip" title="<?= $this->text->markdownAttribute($description) ?>">
            <i class="fa fa-info-circle"></i>
        </small>
    <?php endif ?>
`

my temporary change:
`    <?php if (! empty($description)): ?>
<?=($this->app->tooltipMarkdown($description)); ?>

    <?php endif ?>
`

**Comment by e6nian** [comment]
https://github.com/kanboard/kanboard/commit/5996a8abcf12336586cee345180203dd1500c92f#diff-cbda73c855698dadfdbc565785891f1c
Rewrite tooltips code without jQuery

**Comment by ntimo** [comment]
Are there any news on a fix for this?

**Comment by mpei** [comment]
Is Theme-Plus still developed and will this be fixed? Do we need to fork or has somebody forked with a fix?
