### ISSUE TITLE
Compatibility with kanboard >= 1.0.29

### ISSUE THREAD

**Issue by angystardust** [phsteffen/kanboard-themeplus#4]
Hi @phsteffen , can you please update your plugin to make it work with kanboard >= 1.0.29?
Thanks

**Comment by AZimmerhofer** [comment]
Hi @phsteffen,

are you planning to adapt your theme to 1.0.30?

Alex

**Comment by phsteffen** [comment]
Hi folks,

now the plugin should be running with 1.0.30

Philip

**Comment by angystardust** [comment]
It works! Thank you, @phsteffen
