### ISSUE TITLE
Warrning: filemtime(): stat failed for ....

### ISSUE THREAD

**Issue by lalamax3d** [phsteffen/kanboard-themeplus#6]
Warning: filemtime(): stat failed for assets/css/print.min.css in /home2/lalamax/public_html/board/app/Helper/AssetHelper.php on line 37

i know, you mentioned specific version, just checking on my version 1.0.36
rest works fine. great addition, thanks.

**Comment by phsteffen** [comment]
Hi, with KB 1.0.41 and the new Version of this plugin this should be fixed

**Comment by lalamax3d** [comment]
will check on monday and confirm, thanks in advance.
