### ISSUE TITLE
Header breaks with new in kanboard 1.0.38

### ISSUE THREAD

**Issue by EdwardNavarro** [phsteffen/kanboard-themeplus#7]
Header breaks after upgrade to KB v1.0.38

![screen shot 2017-02-10 at 10 08 56 am](https://cloud.githubusercontent.com/assets/1706334/22831633/149ea2d6-ef79-11e6-8ca1-645641c73cb7.png)

**Comment by juanluisbaptiste** [comment]
I can confirm this.

**Comment by juanluisbaptiste** [comment]
Still happens on 1.0.40.

**Comment by phsteffen** [comment]
With the new Version of the Theme the header should not break anymore in KB v1.0.41
