### ISSUE TITLE
Login Logo is not centered

### ISSUE THREAD

**Issue by ibedon** [phsteffen/kanboard-themeplus#8]

**Comment by ibedon** [comment]
I love this css file however I cant get the logo to be i the middle. Can someone help me with this please?

**Comment by phsteffen** [comment]
Hi, the Easy-Way is:
- Login in Kanboard
- Go to Settings/Application settings
- Put this CSS-Code in the field "Custom Stylesheet":

`#login-top {
    text-align: center;
}`

**Comment by ibedon** [comment]
Thank you so much that did it!!



Sent from my Samsung Galaxy smartphone.

-------- Original message --------
