### ISSUE TITLE
Add Pomodoro Timer in Head section

### ISSUE THREAD

**Issue by Sorasma** [phsteffen/kanboard-themeplus#9]
If possible, can you please also add a pomodoro timer to this theme? This one https://github.com/Buccleuch/pomodoro-timer is very simple, and can be modified easy. Maybe add it like in this img https://app.box.com/s/g5486c4e703bwnl7dmkjifh09rlxcufj 
Thanks :)

**Comment by phsteffen** [comment]
No. Sorry. This is just a Theme for kanboard and provide only visual improvments and no new features.
